# **Data Preprocessing Exercise**

## **Dataset: modified_automobile.csv**


This version of the automobile dataset contains various attributes of automobiles with introduced inconsistencies for the sake of this exercise.

In [11]:
import pandas as pd


modified_df = pd.read_csv('modified_automobile.csv')
modified_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,NaN,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
1,1,128.0,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,NaN,5200.0,31,37,7799.0
2,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
3,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,NaN,4800.0,28,34,9258.0
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0

### 1. **Handling Missing Values**

In [12]:
count_missing_values = modified_df.isnull().sum()

In [13]:
modified_df_dropna = modified_df.dropna()

In [14]:
modified_df_dropna.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0
5,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
6,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.0,101.0,5800.0,24,28,12945.0
7,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
8,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68.0,4500.0,37,42,9495.0

In [15]:
modified_df_fill_mean = modified_df.fillna(modified_df.mean(numeric_only=True))

In [16]:
modified_df_fill_median = modified_df.fillna(modified_df.median())

/var/folders/cm/tp384c9x4q78rhtw47g1d4800000gn/T/ipykernel_2536/2410914134.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  modified_df_fill_median = modified_df.fillna(modified_df.median())

In [17]:
modified_df_dropna.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0
5,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
6,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.0,101.0,5800.0,24,28,12945.0
7,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
8,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68.0,4500.0,37,42,9495.0

In [18]:
modified_df_fill_mean.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,121.964497,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.000000,4200.0,31,39,18344.0
1,1,128.000000,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,132.797753,5200.0,31,37,7799.0
2,-1,121.964497,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.000000,5200.0,19,24,15750.0
3,0,91.000000,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,132.797753,4800.0,28,34,9258.0
4,0,77.000000,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.000000,4800.0,31,37,6918.0

In [19]:
modified_df_fill_median.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,115.0,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
1,1,128.0,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,102.0,5200.0,31,37,7799.0
2,-1,115.0,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
3,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,102.0,4800.0,28,34,9258.0
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0

### 2. **Removing Duplicates**

In [20]:
initial_count = len(modified_df)
modified_df = modified_df.drop_duplicates()
remaining_count = len(modified_df)

initial_count, remaining_count

(210, 204)

### 3. **Correcting Inconsistent Values**

In [21]:
inconsistent_values = modified_df['fuel-type'].value_counts()

modified_df['fuel-type'] = modified_df['fuel-type'].replace('water', 'gas')

inconsistent_values, modified_df['fuel-type'].value_counts()

(gas       180
 diesel     20
 water       4
 Name: fuel-type, dtype: int64,
 gas       184
 diesel     20
 Name: fuel-type, dtype: int64)

### 4. **Handling Outliers**

Interquartile Range (IQR) can be used to detect outliers. A common rule of thumb is that any data point that falls below Q1 - 1.5 x IQR or above Q3 + 1.5 X IQR might be considedred an outlier.

In [22]:
# Use IQR to identify and remove outliers in the 'price' column
Q1 = modified_df['price'].quantile(0.25)
Q3 = modified_df['price'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers
modified_df_no_outliers = modified_df[(modified_df['price'] >= lower_bound) & (modified_df['price'] <= upper_bound)]

len(modified_df), len(modified_df_no_outliers)

(204, 171)